# 线性代数

## 标量 由只有一个元素的张量表示

In [1]:
import torch

x=torch.tensor([3.0])
y=torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 可将向量视为标量组成的列表

In [3]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

## 通过张量的索引来访问任一元素

In [4]:
x[3]

tensor(3)

## 访问张量的长度

In [5]:
len(x)

4

## 只有一个轴的张量，形状只有一个元素

In [6]:
x.shape

torch.Size([4])

## 通过指定两个分量m和n来创建一个形状为m x n的矩阵

In [8]:
A=torch.arange(20).reshape(4,5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

## 矩阵的转置

In [9]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

## 对称矩阵 A=其转置

In [10]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 向量是标量的推广，矩阵是向量的推广

In [13]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [14]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()  # 通过分配新的内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 两个矩阵的按元素乘法成为 哈达玛积（Hadamard Product） 

In [15]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [16]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))