# 线性代数

## 标量 由只有一个元素的张量表示

In [29]:
import torch

x=torch.tensor([3.0])
y=torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 可将向量视为标量组成的列表

In [30]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

## 通过张量的索引来访问任一元素

In [31]:
x[3]

tensor(3)

## 访问张量的长度

In [32]:
len(x)

4

## 只有一个轴的张量，形状只有一个元素

In [33]:
x.shape

torch.Size([4])

## 通过指定两个分量m和n来创建一个形状为m x n的矩阵

In [34]:
A=torch.arange(20).reshape(4,5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

## 矩阵的转置

In [35]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

## 对称矩阵 A=其转置

In [36]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [37]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 向量是标量的推广，矩阵是向量的推广

In [38]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [39]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()  # 通过分配新的内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 两个矩阵的按元素乘法成为 哈达玛积（Hadamard Product） 

In [40]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [41]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 计算其元素的和

In [42]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()


(tensor([0., 1., 2., 3.]), tensor(6.))

## 表示任意形状张量的元素之和

In [43]:
A=torch.arange(20*2).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780))

## 指定求和汇总张量的轴

In [44]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [45]:
A_sum_axis1=A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [46]:
A.sum(axis=[0,1]) #same as A.sum()

tensor([180, 190, 200, 210])

## 平均值（mean或average）

In [47]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [48]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

## 计算总和或者均值时保持轴数不变

In [49]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

## 通过广播将A除以sum_A


In [50]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

##  某个轴计算A元素的累积总和

In [51]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积是相同位置的元素乘积之和

In [52]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

## 矩阵向量积Ax是一个长度为m的列向量（mv-matrix vector multiplication）

In [53]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n x m 矩阵

In [54]:
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])